version: '3'

services:
  kafka-zookeeper:                                                                                                            
    image: confluentinc/cp-zookeeper:7.3.0                                                                              
    container_name: kafka-zookeeper                                                                                           
    environment:                                                                                                        
      ZOOKEEPER_CLIENT_PORT: 2181                                                                                       
      ZOOKEEPER_TICK_TIME: 2000                                                                                         
                                                                                                                        
  kafka-broker:                                                                                                               
    image: confluentinc/cp-kafka:7.3.0                                                                                  
    container_name: kafka-broker                                                                                              
    ports:                                                                                                              
      - "9092:9092"                                                                                                     
      - "29092:29092"                                                                                                     
      - "29093:39093"                                                                                                     
    depends_on:                                                                                                         
      - kafka-zookeeper                                                                                                       
    environment:                                                                                                        
      KAFKA_BROKER_ID: 1                                                                                                
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'                                                                         
      ALLOW_PLAINTEXT_LISTENERS: 'yes'
        # KAFKA_LISTENERS: PLAINTEXT://:9092
        # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
        # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT                            
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092,PLAINTEXT_EXT://127.0.0.1:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

